<a href="https://colab.research.google.com/github/Hena-123/095_HenaPatel/blob/main/lab1_Preprocesssing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

**1) Create Two numpy array of size 3 X 2 and 2 X 3**

**2) Randomly Initalize that array**

In [ ]:
narray1 = np.array([1,2])
narray2 = np.array([1,2,3])

matrix1 = np.array([narray1,narray1+1,narray1+2])
matrix2 = np.array([narray2,narray2+2])
print(matrix1)
print(matrix2)

[[1 2]
 [2 3]
 [3 4]]
[[1 2 3]
 [3 4 5]]


**3) Perform matrix multiplication**

In [ ]:
np.matmul(matrix1,matrix2)

array([[ 7, 10, 13],
       [11, 16, 21],
       [15, 22, 29]])

**4) Perform elementwise matrix multiplication**

In [ ]:
matrix1 * matrix2

ValueError: ignored

Here for elementwise matrix multiplication, both matrix must have same no of element in each row. Matrix1 is off 3 X 2 and matrix2 is off 2 X 3.

In [ ]:
m1 = np.array([narray1,narray1+1,])
m2 = np.array([narray1+1,narray1+2])
print(m1,"\n")
print(m2,"\n")
print(m1 * m2)

[[1 2]
 [2 3]] 

[[2 3]
 [3 4]] 

[[ 2  6]
 [ 6 12]]


**5) Find mean of first matrix**

In [ ]:
np.mean(matrix1)

2.5

**6) Convert Numeric entries(columns) of mtcars.csv to Mean Centered Version**

In [ ]:
import pandas as pd
data=pd.read_csv('./Exercise-CarData.csv')

In [ ]:
meanCenteredVersion = data['Price'] - np.mean(data['Price'],axis=0)
print(meanCenteredVersion)

0       2769.175487
1       3019.175487
2       3219.175487
3       4219.175487
4       3019.175487
           ...     
1431   -3230.824513
1432     114.175487
1433   -2230.824513
1434   -3480.824513
1435   -3780.824513
Name: Price, Length: 1436, dtype: float64


In [ ]:
sumof_meanCenteredVersion = np.sum(meanCenteredVersion,axis=0)
print(sumof_meanCenteredVersion)

4.656612873077393e-10


Here sumof_meanCenteredVersion is 4.6 X 10^-10 which is nearer to 0 which shows that Price Column is mean cenetered version.